version: "3.5"

services:
  nginx_test: # Only for local development
    image: "fastapi_bldg_nginx_dev:0.1.0"
    container_name: "volleyapp_nginx_dev_test"
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - "22444:80"
    volumes:
      - ./htdocs/:/usr/share/nginx/html
    networks:
      - volley_network
    environment:
      APP_ENV: "test"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.test.local
  api_test:
    image: "fastapi_bldg_dev:0.1.0"
    container_name: "fastapi_bldg_test"
    depends_on:
      - db_test
      - nginx_test
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    ports:
      - "20444:8000"
    volumes:
      - ./app:/usr/src/app/app
      - ./db:/usr/src/app/db
      - ./scripts:/usr/src/app/scripts
      - ./tests:/usr/src/app/tests
      - ./htdocs:/usr/src/app/htdocs
      - ./log/app:/var/log/app
    working_dir: /usr/src/app/scripts
    command: bash -c "./init_db.sh && ./run_server.sh && ../tests/scripts/run_seed.sh"
    networks:
      - volley_network
    environment:
      APP_ENV: "test"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.test.local
  db_test:
    image: "volleyapp_db_dev:0.1.0"
    container_name: "volleyapp_db_test"
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - "21444:3306"
    volumes:
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./log/db:/var/log/mysql
    networks:
      - volley_network
    environment:
      APP_ENV: "test"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.test.local

networks:
  default:
    external:
      name: bridge
  volley_network:
    name: volley_network
    driver: bridge
    external: true
