version: "3.5"

services:
  nginx: # Only for local development
    image: "volleyapp_nginx_dev:0.1.0"
    container_name: "volleyapp_nginx_dev"
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - "12444:80"
    volumes:
      - ./htdocs/:/usr/share/nginx/html
    networks:
      - volley_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.development
  api:
    image: "volleyapp_dev:0.1.0"
    container_name: "volleyapp_dev"
    # depends_on:
    #   - db
    #   - nginx
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    # expose:
    #   - "8000"
    ports:
      - "10444:8000"
    volumes:
      - ./app:/usr/src/app/app:cached
      - ./db:/usr/src/app/db:cached
      - ./scripts:/usr/src/app/scripts:cached
      - ./tests:/usr/src/app/tests:cached
      - ./htdocs:/usr/src/app/htdocs:cached
      - ./log/app:/var/log/app:cached
    working_dir: /usr/src/app/scripts
    command: bash -c "./init_db.sh && ./run_server.sh"
    # networks:
    #   volley_network:
    #     ipv4_address: 172.18.0.3
    networks:
      - volley_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.development
  db:
    image: "volleyapp_db_dev:0.1.0"
    container_name: "volleyapp_db_dev"
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    restart: always
    tty: true
    # expose:
    #   - "3306"
    ports:
      - "11444:3306"
    volumes:
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d:cached
      - ./docker/db/conf.d:/etc/mysql/conf.d:cached
      - ./log/db:/var/log/mysql:cached
    # networks:
    #   volley_network:
    #     ipv4_address: 172.18.0.4
    networks:
      - volley_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.development

networks:
  default:
    external:
      name: bridge
  volley_network:
    name: volley_network
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 172.18.0.0/24
    external: true
