"""add attack time samnail_url

Revision ID: 2029d4e71b74
Revises: 9a8ff159e942
Create Date: 2024-01-01 23:51:15.226083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2029d4e71b74'
down_revision = '9a8ff159e942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attack_times', sa.Column(
        'sumnail_url', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attack_times', 'sumnail_url')
    # ### end Alembic commands ###
