"""add match colmun

Revision ID: 318564a3085d
Revises: c818b5f21065
Create Date: 2023-11-26 14:47:54.191493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318564a3085d'
down_revision = 'c818b5f21065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchs', sa.Column(
        'season_id', sa.String(length=225), nullable=False))
    op.create_foreign_key(op.f('fk_matchs_season_id_seasons'),
                          'matchs', 'seasons', ['season_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_matchs_season_id_seasons'),
                       'matchs', type_='foreignkey')
    op.drop_column('matchs', 'season_id')
    # ### end Alembic commands ###
