"""update

Revision ID: 3bf113fdd508
Revises: fa9969f0ca4f
Create Date: 2023-12-13 01:12:11.035842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = '3bf113fdd508'
down_revision = 'fa9969f0ca4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_set_score',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('match_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('score_team_home', sa.Integer(), nullable=False),
    sa.Column('score_team_away', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matchs.uuid'], name=op.f('fk_match_set_score_match_id_matchs')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_match_set_score'))
    )
    op.add_column('attacks', sa.Column('away_team_set_score', sa.Integer(), nullable=False))
    op.add_column('attacks', sa.Column('home_team_set_score', sa.Integer(), nullable=False))
    op.add_column('match_scores', sa.Column('match_set_score_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False))
    op.add_column('match_scores', sa.Column('score_team_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False))
    op.add_column('match_scores', sa.Column('sequence_number', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_match_scores_match_set_score_id_match_set_score'), 'match_scores', 'match_set_score', ['match_set_score_id'], ['uuid'])
    op.create_foreign_key(op.f('fk_match_scores_score_team_id_teams'), 'match_scores', 'teams', ['score_team_id'], ['uuid'])
    op.drop_constraint('fk_matchs_matchscore_id_match_scores', 'matchs', type_='foreignkey')
    op.drop_column('matchs', 'matchscore_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchs', sa.Column('matchscore_id', mysql.VARCHAR(length=225), nullable=False))
    op.create_foreign_key('fk_matchs_matchscore_id_match_scores', 'matchs', 'match_scores', ['matchscore_id'], ['uuid'])
    op.drop_constraint(op.f('fk_match_scores_score_team_id_teams'), 'match_scores', type_='foreignkey')
    op.drop_constraint(op.f('fk_match_scores_match_set_score_id_match_set_score'), 'match_scores', type_='foreignkey')
    op.drop_column('match_scores', 'sequence_number')
    op.drop_column('match_scores', 'score_team_id')
    op.drop_column('match_scores', 'match_set_score_id')
    op.drop_column('attacks', 'home_team_set_score')
    op.drop_column('attacks', 'away_team_set_score')
    op.drop_table('match_set_score')
    # ### end Alembic commands ###
