"""create teams

Revision ID: 84762fb2223f
Revises: e19895be23da
Create Date: 2023-11-05 20:05:45.672073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = '84762fb2223f'
down_revision = 'e19895be23da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
                    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text(
                        'current_timestamp'), nullable=False),
                    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text(
                        'current_timestamp on update current_timestamp'), nullable=False),
                    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), default=uuid.uuid4, nullable=False),
                    sa.Column('name', sa.String(length=128), nullable=False),
                    sa.Column('code', sa.String(length=128), nullable=False),
                    sa.Column('director', sa.String(
                        length=128), nullable=True),
                    sa.Column('coach', sa.String(length=128), nullable=True),
                    sa.Column('trainer', sa.String(length=128), nullable=True),
                    sa.Column('doctor', sa.String(length=128), nullable=True),
                    sa.Column('season_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), default=uuid.uuid4, nullable=False),
                    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), default=uuid.uuid4, nullable=False),
                    sa.ForeignKeyConstraint(['season_id'], ['seasons.uuid'], name=op.f(
                        'fk_teams_season_id_seasons')),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.uuid'], name=op.f('fk_teams_user_id_users')),
                    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_teams'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    # ### end Alembic commands ###
