"""create attacktime

Revision ID: 9a8ff159e942
Revises: e32ec177e9d3
Create Date: 2024-01-01 13:20:22.161248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = '9a8ff159e942'
down_revision = 'e32ec177e9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_times',
                    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text(
                        'current_timestamp'), nullable=False),
                    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text(
                        'current_timestamp on update current_timestamp'), nullable=False),
                    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), default=uuid.uuid4, nullable=False),
                    sa.Column('start_time', sa.Integer(), nullable=False),
                    sa.Column('match_id', sqlalchemy_utils.types.uuid.UUIDType(
                        binary=False), default=uuid.uuid4, nullable=False),
                    sa.ForeignKeyConstraint(['match_id'], ['matchs.uuid'], name=op.f(
                        'fk_attack_times_match_id_matchs')),
                    sa.PrimaryKeyConstraint(
                        'uuid', name=op.f('pk_attack_times'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attack_times')
    # ### end Alembic commands ###
