"""create match and playerMatchInfo

Revision ID: c818b5f21065
Revises: 9d8c85a28b03
Create Date: 2023-11-21 15:41:33.394303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = 'c818b5f21065'
down_revision = '9d8c85a28b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('player_number', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('postion', sa.String(length=128), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('team_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('season_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.uuid'], name=op.f('fk_players_season_id_seasons')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.uuid'], name=op.f('fk_players_team_id_teams')),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], name=op.f('fk_players_user_id_users')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_players'))
    )
    op.create_table('playerMatchInfo',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('player_id', sa.String(length=225), nullable=False),
    sa.Column('match_id', sa.String(length=255), nullable=False),
    sa.Column('on_court', sa.Boolean(), nullable=False),
    sa.Column('zone_code', sa.String(length=255), nullable=False),
    sa.Column('libero', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matchs.uuid'], name=op.f('fk_playerMatchInfo_match_id_matchs')),
    sa.ForeignKeyConstraint(['player_id'], ['players.uuid'], name=op.f('fk_playerMatchInfo_player_id_players')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_playerMatchInfo'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playerMatchInfo')
    op.drop_table('players')
    # ### end Alembic commands ###
