"""add start_postion_detection_status column

Revision ID: ddad7ec6a64e
Revises: e32ec177e9d3
Create Date: 2023-12-26 20:10:29.107355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddad7ec6a64e'
down_revision = 'e32ec177e9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchs', sa.Column('start_postion_detection_status', sa.Enum('notStart', 'process', 'finish', name='startpositionstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matchs', 'start_postion_detection_status')
    # ### end Alembic commands ###
