"""create users

Revision ID: e19895be23da
Revises: 
Create Date: 2023-11-03 17:33:15.421943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = 'e19895be23da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('created_at',
                              mysql.TIMESTAMP(),
                              server_default=sa.text('current_timestamp'),
                              nullable=False),
                    sa.Column('updated_at',
                              mysql.TIMESTAMP(),
                              server_default=sa.text(
                                  'current_timestamp on update current_timestamp'),
                              nullable=False),
                    sa.Column('uuid',
                              sqlalchemy_utils.types.uuid.UUIDType(
                                  binary=False),
                              default=uuid.uuid4,
                              nullable=False),
                    sa.Column('username',
                              sa.String(length=128),
                              nullable=False),
                    sa.PrimaryKeyConstraint('uuid',
                                            name=op.f('pk_users'))
                    )
    op.create_table('seasons',
                    sa.Column('created_at',
                              mysql.TIMESTAMP(),
                              server_default=sa.text('current_timestamp'),
                              nullable=False),
                    sa.Column('updated_at',
                              mysql.TIMESTAMP(),
                              server_default=sa.text(
                                  'current_timestamp on update current_timestamp'),
                              nullable=False),
                    sa.Column('uuid',
                              sqlalchemy_utils.types.uuid.UUIDType(
                                  binary=False),
                              default=uuid.uuid4,
                              nullable=False),
                    sa.Column('start_day',
                              sa.DATETIME(),
                              nullable=False),
                    sa.Column('end_day',
                              sa.DATETIME(),
                              nullable=False),
                    sa.Column('season_name',
                              sa.String(length=128),
                              nullable=False),
                    sa.Column('game_format',
                              sa.String(length=128),
                              nullable=False),
                    sa.Column('code',
                              sa.String(length=128),
                              nullable=False),
                    sa.Column('user_id',
                              sqlalchemy_utils.types.uuid.UUIDType(
                                  binary=False),
                              default=uuid.uuid4,
                              nullable=False),
                    sa.ForeignKeyConstraint(['user_id'],
                                            ['users.uuid'],
                                            name=op.f('fk_seasons_user_id_users')),
                    sa.PrimaryKeyConstraint('uuid',
                                            name=op.f('pk_seasons'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seasons')
    op.drop_table('users')
    # ### end Alembic commands ###
