"""create attack table

Revision ID: fa9969f0ca4f
Revises: ca08d0e88eb3
Create Date: 2023-12-12 01:19:46.116828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = 'fa9969f0ca4f'
down_revision = 'ca08d0e88eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attacks',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('home_team_score', sa.Integer(), nullable=False),
    sa.Column('away_team_score', sa.Integer(), nullable=False),
    sa.Column('attack_start_zone', sa.Integer(), nullable=False),
    sa.Column('attack_end_zone', sa.Integer(), nullable=False),
    sa.Column('attack_ball_type', sa.Enum('high', 'medium', 'quick', 'other', name='attackballtype'), nullable=False),
    sa.Column('attack_skill', sa.Enum('headSpike', 'softSpike', 'dink', name='attackskill'), nullable=False),
    sa.Column('attack_evaluation', sa.Enum('kill', 'overPass', 'possibleCover', 'blocked', 'inPlay', 'error', name='attackevaluationtype'), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('match_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('team_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('player_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matchs.uuid'], name=op.f('fk_attacks_match_id_matchs')),
    sa.ForeignKeyConstraint(['player_id'], ['players.uuid'], name=op.f('fk_attacks_player_id_players')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.uuid'], name=op.f('fk_attacks_team_id_teams')),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], name=op.f('fk_attacks_user_id_users')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_attacks'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attacks')
    # ### end Alembic commands ###
